<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicalStudySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('medical_study')->insert([
            // AUDIOMETRIA
            ['description' => 'ACUFENOMETRIA							   ', 'price' => 1500.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'AUDIOMETRIA TONAR LAMINAR                   ', 'price' => 1500.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONTROL DE EPISTAXIS                        ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'CUERPO EXTRAÑO NASAL                        ', 'price' => 800.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'CUERPO EXTRAÑO OTICO                        ', 'price' => 800.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'CURA FARINGITIS CRONICA                     ', 'price' => 300.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'CURA OTOMICOSIS                             ', 'price' => 300.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'EMISIONES OTOACUSTICAS                      ', 'price' => 1500.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'ESTUDIOS DE AUDIOLOGIA                      ', 'price' => 1500.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'HONORARIO MEDICOS OTORRINO                  ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'LAVADO DE OIDO                              ', 'price' => 600.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'LOGOAUDIOMETRIA                             ', 'price' => 1500.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'OTOEMISIONES ACUSTICAS                      ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'POTENCIALES EVOCADOS AUDITIVOS AUDIOLOGIA   ', 'price' => 1500.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'PRUEBA DE FUNCION TUBARICA CON TIMPANOMETRIA', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            ['description' => 'TIMPANOMETRIA							   ', 'price' => 1500.00, 'is_active' => 1, 'catalog_service_id' => 1, 'created_user' => null, 'created_at' => null],
            // CARDIOLOGIA
            ['description' => 'ECO STRAIN 															  ', 'price' => 5000.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ECOCARDIOGRAMA                                                         ', 'price' => 1300.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ECOCARDIOGRAMA DE STRESS CON PRUEBA DE ESFUERZO O CON PRUEBA FARMACOLO ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ECOCARDIOGRAMA MODO M Y BIDIMENSIONAL                                  ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'EEG                                                                    ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ELECTROCARDIOGRAFIA DINAMICA (HOLTER) +                                ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ELECTROCARDIOGRAMA (EKG)                                               ', 'price' => 350.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ELECTROCARDIOGRAMA DE ALTA RESOLUCION                                  ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ELECTROENCEFALOGRAMA EN SUEÑO                                          ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'ELECTROENCEFALOGRAMA PROLONGADO                                        ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'EVALUACION CARDIOVASCULAR                                              ', 'price' => 600.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'HOLTER                                                                 ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'HOLTER 24 HORAS                                                        ', 'price' => 2100.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'MAPA                                                                   ', 'price' => 924.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'MAPA 24 HORAS                                                          ', 'price' => 2100.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'MONITOR DE PRESION 24 HORAS) MAPA                                      ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'PRUEBA DE ESFUERZO                                                     ', 'price' => 1100.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],
            ['description' => 'UROGRAFIA INCLUYENDO PROCEDIMIENTO DE LA INYECCION                     ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 3, 'created_user' => null, 'created_at' => null],

            // CIRUGIA MENOR
            ['description' => 'CURA DE HERIDA BAJO ANESTESIA ', 'price' => 10000.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            ['description' => 'CURA DE HERIDA QUIRURGICA     ', 'price' => 2000.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            ['description' => 'DRENAJE DE ABSCESO            ', 'price' => 7200.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            ['description' => 'DRENAJE DE SEROMA             ', 'price' => 9600.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            ['description' => 'EXERESIS DE VERRUGA           ', 'price' => 6400.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            ['description' => 'LOBULOPLASTIA                 ', 'price' => 12800.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            ['description' => 'Retiro cuerpo extraño         ', 'price' => 1000.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            ['description' => 'TOMA DE CULTIVO               ', 'price' => 5600.00, 'is_active' => 1, 'catalog_service_id' => 4, 'created_user' => null, 'created_at' => NOW()],
            // CONSULTA MÉDICA
            ['description' => 'AXILAS                                                            ', 'price' => 300.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'BLANQUIAMIENTO DE AXILAS 2 SECCIONES                              ', 'price' => 700.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'BLANQUIAMIENTO DE CUELLO 2 SECCIONES                              ', 'price' => 700.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CERTIFICADO MEDICO                                                ', 'price' => 150.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSLTA MEDICO NUTRICIONISTA                                      ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA                                                          ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA AMBULATORIA                                              ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA DE GINECOLOGIA                                           ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA DE PSICOLOGIA                                            ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA DERMATOLOGÍA                                             ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA EN EMERGENCIA                                            ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ENDOCRINOLOGÍA                                           ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA GINECO OBSTETRICIA                                       ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA GINECOLOGIA ONCOLOGICA                                   ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA INFECTOLOGIA PEDIATRICA                                  ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICINA GENERAL                                         ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICINA INTERNA                                         ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO CARDIOLOGO                                        ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO DIABETOLOGIA                                      ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO ESPECIALIZADA                                     ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO FAMILIAR                                          ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO FISIATRA                                          ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO GASTROENTEROLOGO                                  ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO GINECOBSTETRA                                     ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO INTERNISTA                                        ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO ORTOPEDISTA Y TRAUMATOLOGO                        ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO PEDIATRA                                          ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO PSICOLOGO                                         ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO PSIQUIATRIA                                       ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO TERAPEUTA FAMILIAR                                ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO UROLOGO                                           ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA NEUMOLOGÍA                                               ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA NUTRICION                                                ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA NUTRICION PEDIATRICA                                     ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ODONTOLOGICA                                             ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ODONTOLOGICA EMERGENCIA O URGENCIAS                      ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ODONTOLOGICA ESPECIALIZADA                               ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ODONTOLOGICA GENERAL                                     ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA OFTALMOLOGIA                                             ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ORTOPEDIA                                                ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA OTORRINOLARINGOLOGIA                                     ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA POR PRIMERA VEZ DE FISIOTERAPIA                          ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA PRE-ANESTESICA                                           ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA PSICOLOGA CLINICA                                        ', 'price' => 200.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA PSIQUIATRICA                                             ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA REHABILITACION                                           ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA UROLOGIA                                                 ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA CIRUGIA MAXILOFACIAL                                     ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA DE PRIMERA VEZ POR FISIOTERAPIA                          ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ENDODONCIA                                               ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ENEMERGENCIA                                             ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICINAGENERAL                                          ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO CARDIOLOGO                                        ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO FISIATRIA                                         ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO GASTROENTEROLOGO                                  ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO GINECOBSTETRA                                     ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO INTERNISTA                                        ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO NUTRICIONISTAY DIETISTA                           ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO ORTOPEDISTAYTRAUMATOLOGO                          ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA MEDICO PEDIATRIA                                         ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ODONTOPEDIATRIA                                          ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA ORTODONCIA                                               ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA PERIDONCIA                                               ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONSULTA PROTESIS, CORONAS Y PUENTES                              ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'CONTROL DE PLACA DENTAL NCOC                                      ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'DESTARTRAJE SUPRAGINGIVAL SOD +                                   ', 'price' => 2000.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'DETARTRAJE SUBGINGIVAL  PROFILAXIS                                ', 'price' => 2000.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'EVALUACION DE ANESTESIOLOGIA                                      ', 'price' => 600.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'EXTIRPACION DE VERRUGAS                                           ', 'price' => 400.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'HERMATOLOGIA                                                      ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'LIMPIEZA + MASCARILLA DE VITAMINA CCON ACIDO HIALURONICO + PEELING', 'price' => 750.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'LIMPIEZA + PEELING + DEPILACION DE CEJAS Y BIGOTE                 ', 'price' => 600.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'LIMPIEZA + PEELING + MASCARILLA HIDRATANTE + DEPILACION DE CEJAS  ', 'price' => 550.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'LIMPIEZA PROFUNDA CON MASCARILLA REGENERADORA                     ', 'price' => 450.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'LIMPIEZA PROFUNDA CON SCRUB Y MASCARILLA                          ', 'price' => 450.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'MICRO + MASCARILLA                                                ', 'price' => 700.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'PAPMPER                                                           ', 'price' => 100.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'PEELING + MASCARILLA + DEPILACION DE EJAS                         ', 'price' => 550.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'PEELING + MASCARILLA ASTRINGENTE + DEPILACION DE CEJAS            ', 'price' => 550.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'PIERNAS                                                           ', 'price' => 500.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            ['description' => 'VIQUINI															 ', 'price' => 500.00, 'is_active' => 1, 'catalog_service_id' => 5, 'created_user' => null, 'created_at' => null],
            // DERMATOLOGIA
            ['description' => 'APLICACIÓN DE ACIDO TRICLOROACETICO EN VERRUGAS A		   ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],
            ['description' => 'APLICACIÓN DE ACIDO TRICLOROACETICO EN VERRUGAS ANOGENITALES', 'price' => 1600.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],
            ['description' => 'APLICACIÓN DE TRIANCINOLONA DE QUELOIDES/ QUITES SE         ', 'price' => 0.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],
            ['description' => 'APLICACIÓN DE TRIANCINOLONA DE QUELOIDES/ QUITES SEBACEOS   ', 'price' => 900.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],
            ['description' => 'MASCARILLA                                                  ', 'price' => 150.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],
            ['description' => 'RESECCION DE QUERATOSIS SEBORREICA                          ', 'price' => 2100.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],
            ['description' => 'RESECCION MOLUSCO CONTAGIOSO                                ', 'price' => 2600.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],
            ['description' => 'RESECCION VERRUGA VULGAR                                    ', 'price' => 2600.00, 'is_active' => 1, 'catalog_service_id' => 7, 'created_user' => null, 'created_at' => null],

        ]);
    }
}
